version: "3.8"
services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../app:/usr/src/app/

    working_dir: /usr/src/app/design_system

    tty: true



